version: '3.3'
services:
  blog-api:
    build: .
    container_name: blog-server
    ports:
      - '800:800'
    volumes:
      - ./data:/app/data
    networks:
      - my-network
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: blog_db
      MySQL_USER: dev1
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - localMysqlData:/var/lib/mysql
volumes:
  localMysqlData:

networks:
  my-network:
    external: true