version: '3.3'
services:
  blog-api:
    build: .
    container_name: blog-server
    ports:
      - '800:800'
    volumes:
      - ./data:/app/data
    networks:
        - my-network
volumes:
  localMysqlData:
networks:
    my-network:
        external: true