spring:
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    password: lmnlqslgrqmeibxi
    username: gabtaninw
    port: 587
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  datasource:
    url: jdbc:mysql://103.99.11.176:3306/blog_db?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 3jhk09fvnDJT2w0n6y084Ma5gQzy2J
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  cache:
    redis:
      time-to-live: 60000
  redis:
    host: 103.99.11.176
    port: 6379
    password: X4FDKdvs57ut5GiYtz456U86aDxc6M
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
jwt:
  issuer: yutsuki
  expirationMs: 1h
  isExpire: 1
server:
  whitelist: /error,/v1/auth/**,/ws/**,/v1/upload/**,/ping/**
  resetTokenExpire: 30
  port: 800
storage:
  location: /app/data/images
  compressQuality: 0.7
email:
  reset-password-form: /app/data/reset-password.html
  reset-password-url: https://blog.yotsuki.online/reset-password?code=
logging:
  level:
    com.yutsuki.serverApi: debug
