spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useUnicode=yes&characterEncoding=UTF-8
    username: dev1
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  cache:
    redis:
      time-to-live: 60000
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
jwt:
  issuer: yotsuki
  expirationMs: 1h
  isExpire: 1
server:
  whitelist: /v1/auth/**,/ws/**,/v1/upload/**
  origins: http://localhost:[*], http://*.your-domain.com:[*]
storage:
  location: D:\image
logging:
  level:
    com.yutsuki.serverApi: debug
