spring:
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    password: lmnlqslgrqmeibxi
    username: gabtaninw@gmail.com
    port: 587
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useUnicode=yes&characterEncoding=UTF-8
    username: dev1
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  cache:
    redis:
      time-to-live: 60000
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
jwt:
  issuer: yutsuki
  expirationMs: 4h
  isExpire: 1
server:
  whitelist: /v1/auth/**,/v1/forgot-password/**,/swagger-resources/**,/swagger-ui/**,/v*/api-docs,/error
  origins: http://localhost:[*]
  resetTokenExpire: 30
  port: 8080
storage:
  location: D:\image
email:
  reset-password-form: classpath:email/reset-password.html
  reset-password-url: http://localhost:3000/reset-password?token=
logging:
  level:
    com.yutsuki.serverApi: debug
    #    org.springframework.security: debug
    org:
      springframework:
        transaction: debug




